apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: example-secret
stringData:
  key: i_am_kaney_west
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment1
  name: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - image: ghcr.io/valkiriaaquatica/nginx:0.0.2
        imagePullPolicy: IfNotPresent
        name: deployment1
      imagePullSecrets: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment1
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - image: ghcr.io/valkiriaaquatica/nginx2:0.0.1
        imagePullPolicy: IfNotPresent
        name: deployment2
      imagePullSecrets: null
